En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [3]:
A = [ [4, -1, 2], [1, 2, 3], [1, 1, -1] ]
B = [ [-3, -1, 3], [2, 2, 2], [-9, 7, 9] ]
 
n=len(A) # nombre de lignes
m=len(A[0]) # nombre de colonnes
 
C = [[0]*m for i in range(n)] # matrice de b lignes et m colonnes
 
for i in range(n):
    for j in range(m):
        C[i][j]= A[i][j] + B[i][j]
 
print("A : ", A)
print("B : ", B)
print("A + B : ", C)      

A :  [[4, -1, 2], [1, 2, 3], [1, 1, -1]]
B :  [[-3, -1, 3], [2, 2, 2], [-9, 7, 9]]
A + B :  [[1, -2, 5], [3, 4, 5], [-8, 8, 8]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [14]:
import numpy as np

A = np.array([ [4, -1, 2], [1, 2, 3], [1, 1, -1] ])
B = np.array([ [-3, -1, 3], [2, 2, 2], [-9, 7, 9] ])
 
C = A.dot(B)
 
print("A : \n", A)
print("B : \n", B)
print("A * B : \n", C)

A : 
 [[ 4 -1  2]
 [ 1  2  3]
 [ 1  1 -1]]
B : 
 [[-3 -1  3]
 [ 2  2  2]
 [-9  7  9]]
A * B : 
 [[-32   8  28]
 [-26  24  34]
 [  8  -6  -4]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [16]:
P = [ [1, 0, 0], [0, 1, 0], [0, 0, 1] ]

n=len(P)
m=m1=m2=0
l=l1=l2=0

for i in range(n):
    m=m+P[0][i]
    m1=m1+P[1][i]
    m2=m2+P[2][i]
    l=l+P[i][0]
    l1=l1+P[i][1]
    l2=l2+P[i][2]

if m==1 and m1==1 and m2==1:
    print("La matrice P est stochastique \n")
    if l==1 and l1==1 and l2==1:
        print("La matrice P est Bistochastique \n")
else :
    print("La matrice est normale")

La matrice P est stochastique 

La matrice P est Bistochastique 



Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [19]:
A = np.array([ [3, 1], [9, 8] ])
 
C = A.transpose()
 
print("A : \n", A)
print("Transposée de A : \n", C)

A : 
 [[3 1]
 [9 8]]
Transposée de A : 
 [[3 9]
 [1 8]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)